// ---------------------------------------------------------------------------
// Rendering only — talks to the DOM, delegates all logic to engine.js.
// ---------------------------------------------------------------------------

function renderConstraints() {
  const el = document.getElementById("constraints");
  el.innerHTML = `
    <span>👥 ${CONSTRAINTS.staffAvailable} staff available</span>
    <span>📅 ${CONSTRAINTS.slotsRemainingToday} slots left today</span>
    <span>🔒 Refunds require manager approval</span>
    <span>⭐ VIP list loaded (${VIP_LIST.length})</span>
    <span>📚 Knowledge base loaded</span>
  `;
}

function renderBanner(message, mode) {
  const el = document.getElementById("banner");
  if (!message) {
    el.style.display = "none";
    return;
  }
  el.style.display = "block";
  el.textContent = message;
  el.className = `banner banner-${mode}`;
}

async function fetchAIDecisions() {
  const res = await fetch("/api/triage", { method: "POST" });
  const data = await res.json();
  if (!data.ok) throw new Error(data.error || "AI triage request failed");
  return data.decisions;
}

function renderRequests(decisions) {
  const el = document.getElementById("requests");
  el.innerHTML = decisions
    .map(
      (d) => `
    <div class="card">
      <div class="card-head">
        <div class="title-block">
          <div class="rank-badge">P${d.priorityRank}</div>
          <div>
            <h2>${d.customer}</h2>
            <div class="summary">${d.summary}</div>
          </div>
        </div>
        <div class="badges">
          <span class="badge owner-${d.owner}">${d.owner}${d.autonomous ? " · auto" : ""}</span>
        </div>
      </div>

      <div class="grid-row">
        <div class="label">Confidence</div>
        <div class="value">
          ${d.confidence}%
          <div class="confidence-bar-wrap"><div class="confidence-bar" style="width:${d.confidence}%"></div></div>
        </div>

        <div class="label">Action</div>
        <div class="value">${d.action}</div>

        <div class="label">Response</div>
        <div class="value"><div class="response-box">${d.response}</div></div>

        <div class="label">Reasoning</div>
        <div class="value">${d.reasoning} (priority score: ${d.priorityScore}/100)</div>
      </div>
    </div>`
    )
    .join("");
}

async function main() {
  renderConstraints();
  renderBanner("Asking Claude to assess each request live…", "loading");
  try {
    const decisions = await fetchAIDecisions();
    renderBanner(`Live — confidence, response & reasoning generated by Claude per request. Priority and AI/Staff/Manager routing are still enforced by fixed business rules.`, "ok");
    renderRequests(decisions);
  } catch (err) {
    renderBanner(`AI service unavailable (${err.message}) — showing offline rule-based fallback.`, "error");
    const decisions = triage(REQUESTS, CONSTRAINTS, KNOWLEDGE_BASE);
    renderRequests(decisions);
  }
}

document.addEventListener("DOMContentLoaded", main);
